[package]
name = "wallhaven_browser"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
select = "0.6.0"
eframe = "0.28.1"
egui = "0.28.1"
open = "5.3.0"
image = "0.25.2"
crossbeam = "0.8.0"
anyhow = "1.0"